

## Here we show a test vignette for trying out this package:

```{r}
devtools::install_github("surbut/MSGene")
library(MSGene)
```

# load our data
```{r}
data("testdf")
```
# set a training set
```{r}
train=df2[1:(nrow(df2)*0.80),]
```
# specify ages and states
```{r}
ages=c(40:80)
nstates=c("Health", "Ht","HyperLip","Dm","Cad","death","Ht&HyperLip","HyperLip&Dm","Ht&Dm","Ht&HyperLip&Dm")
```

## Fit our model

```{r}

modelfit = fitfunc2(
  df_frame=data.table::data.table(train),
  ages = ages,
  nstates = nstates,
  mode = "binomial",
  covariates = "cad.prs+f.31.0.0+smoke+antihtn_now+statin_now")
```


## Extract coefficients for health-->CAD transition
```{r}
a = coefplotsmooth2(
    ages = ages,
    start = nstates[1],
    stop = "Cad",
    modelfit = modelfit,
    window_width = 20,
    span = 0.75,
    degree = 2
  )
healthy_coefs = a$custom_smooth
```

```{r}
## create sample matrix to test

intercept=1
cad.prs=c(-2,-1,0,1,2)
sex=c(0,1)
smoke=c(0,1)
antihtn_now=c(0,1)
statin_now=c(0,1)
atrisk=expand.grid(intercept,cad.prs,sex,smoke,antihtn_now,statin_now)


mso = compute_prediction_product_matrix(
coefmat = healthy_coefs,
atrisk = atrisk,
agepredinterval = c(40:80)
)
```
# remaining lifetime risk matrix starting from each 40 for all 80 individuals in the profile

```{r}
mso$PredictedIntervalrisk
```

# remaining lifetime risk matrix under treatment starting from 40

```{r}
mso$Hazard_treated
```


